// <auto-generated />
using System;
using DrasiWake.Persistence.SonnetDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrasiWake.Persistence.SonnetDB.Migrations
{
    [DbContext(typeof(BridgeDbContext))]
    partial class BridgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DrasiWake.Persistence.SonnetDB.Entities.KeyMapping", b =>
                {
                    b.Property<string>("ContractScope")
                        .HasMaxLength(512)
                        .HasColumnType("STRING");

                    b.Property<string>("CanonicalIdentity")
                        .HasMaxLength(2048)
                        .HasColumnType("STRING");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("STRING");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("STRING");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("DATETIME");

                    b.HasKey("ContractScope", "CanonicalIdentity");

                    b.ToTable("KeyMappings", (string)null);
                });

            modelBuilder.Entity("DrasiWake.Persistence.SonnetDB.Entities.SnapshotCheckpoint", b =>
                {
                    b.Property<string>("BindingId")
                        .HasMaxLength(512)
                        .HasColumnType("STRING");

                    b.Property<string>("SessionId")
                        .HasMaxLength(2048)
                        .HasColumnType("STRING");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("STRING");

                    b.HasKey("BindingId", "SessionId");

                    b.ToTable("SnapshotCheckpoints", (string)null);
                });

            modelBuilder.Entity("DrasiWake.Persistence.SonnetDB.Entities.SubscriptionState", b =>
                {
                    b.Property<string>("QueryKey")
                        .HasMaxLength(2048)
                        .HasColumnType("STRING");

                    b.Property<string>("InstanceId")
                        .HasMaxLength(512)
                        .HasColumnType("STRING");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("BOOL");

                    b.Property<DateTimeOffset?>("LastConnectedAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(256)
                        .HasColumnType("STRING");

                    b.Property<DateTimeOffset?>("LastReconciledAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<string>("QueryId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("STRING");

                    b.Property<string>("ServerUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("STRING");

                    b.HasKey("QueryKey");

                    b.HasIndex("ServerUri", "InstanceId", "QueryId")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("DrasiWake.Persistence.SonnetDB.Entities.WakeOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("STRING");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INT");

                    b.Property<string>("BindingId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("STRING");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("STRING");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("STRING");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("STRING");

                    b.Property<string>("InvocationId")
                        .HasMaxLength(512)
                        .HasColumnType("STRING");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(256)
                        .HasColumnType("STRING");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("DATETIME");

                    b.Property<DateTimeOffset?>("RetainUntilUtc")
                        .HasColumnType("DATETIME");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("STRING");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("STRING");

                    b.Property<string>("SnapshotFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("STRING");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<string>("TraceId")
                        .HasMaxLength(256)
                        .HasColumnType("STRING");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("NextAttemptAtUtc", "CreatedAtUtc", "Id");

                    b.ToTable("WakeOutbox", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
